package com.common;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.model.*;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		//arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("item", "itemId", Item.class);
		arp.addMapping("picture", "id", Picture.class);
		arp.addMapping("upload", "uploadid", Upload.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("log", "id", Log.class);
		arp.addMapping("test", "testId", Test.class);
		arp.addMapping("book", "id", Book.class);
	}
}

