package com.model.pojo;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUpload<M extends BaseUpload<M>> extends Model<M> implements IBean {

	public M setUploadid(java.lang.Long uploadid) {
		set("uploadid", uploadid);
		return (M)this;
	}

	public java.lang.Long getUploadid() {
		return getLong("uploadid");
	}

	public M setBusinessType(java.lang.String businessType) {
		set("businessType", businessType);
		return (M)this;
	}

	public java.lang.String getBusinessType() {
		return getStr("businessType");
	}

	public M setOriginalFileName(java.lang.String originalFileName) {
		set("originalFileName", originalFileName);
		return (M)this;
	}

	public java.lang.String getOriginalFileName() {
		return getStr("originalFileName");
	}

	public M setFileName(java.lang.String fileName) {
		set("fileName", fileName);
		return (M)this;
	}

	public java.lang.String getFileName() {
		return getStr("fileName");
	}

	public M setContentType(java.lang.String contentType) {
		set("contentType", contentType);
		return (M)this;
	}

	public java.lang.String getContentType() {
		return getStr("contentType");
	}

}
