package com.model.pojo;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseItem<M extends BaseItem<M>> extends Model<M> implements IBean {

	public M setItemId(java.lang.Long itemId) {
		set("itemId", itemId);
		return (M)this;
	}

	public java.lang.Long getItemId() {
		return getLong("itemId");
	}

	public M setItemCode(java.lang.String itemCode) {
		set("itemCode", itemCode);
		return (M)this;
	}

	public java.lang.String getItemCode() {
		return getStr("itemCode");
	}

	public M setItemSup(java.lang.String itemSup) {
		set("itemSup", itemSup);
		return (M)this;
	}

	public java.lang.String getItemSup() {
		return getStr("itemSup");
	}

	public M setItemName(java.lang.String itemName) {
		set("itemName", itemName);
		return (M)this;
	}

	public java.lang.String getItemName() {
		return getStr("itemName");
	}

	public M setItemUrl(java.lang.String itemUrl) {
		set("itemUrl", itemUrl);
		return (M)this;
	}

	public java.lang.String getItemUrl() {
		return getStr("itemUrl");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setEnable(java.lang.String enable) {
		set("enable", enable);
		return (M)this;
	}

	public java.lang.String getEnable() {
		return getStr("enable");
	}

	public M setItemSub(java.lang.String itemSub) {
		set("itemSub", itemSub);
		return (M)this;
	}

	public java.lang.String getItemSub() {
		return getStr("itemSub");
	}

}
