package com.model.pojo;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserTokens<M extends BaseUserTokens<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}

	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	public M setUserAgent(java.lang.String userAgent) {
		set("userAgent", userAgent);
		return (M)this;
	}

	public java.lang.String getUserAgent() {
		return getStr("userAgent");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}

	public java.lang.String getToken() {
		return getStr("token");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return getStr("type");
	}

	public M setCreated(java.lang.Integer created) {
		set("created", created);
		return (M)this;
	}

	public java.lang.Integer getCreated() {
		return getInt("created");
	}

	public M setExpires(java.lang.Integer expires) {
		set("expires", expires);
		return (M)this;
	}

	public java.lang.Integer getExpires() {
		return getInt("expires");
	}

}
