package com.model.pojo;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTest<M extends BaseTest<M>> extends Model<M> implements IBean {

	public M setTestId(java.lang.Long testId) {
		set("testId", testId);
		return (M)this;
	}

	public java.lang.Long getTestId() {
		return getLong("testId");
	}

	public M setBook(java.lang.String book) {
		set("book", book);
		return (M)this;
	}

	public java.lang.String getBook() {
		return getStr("book");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return getStr("password");
	}

}
