package com.phantom.jfinal.tool;

import com.common.model.Blog;
import com.common.model.Register;
import com.common.model.Role;
import com.common.model.User;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("register", "id", Register.class);
	}
}

