package com.model;

import com.model.pojo.BaseBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Banner extends BaseBanner<Banner> {
	public static final Banner dao = new Banner().dao();
}
