package com.model;

import com.model.pojo.BaseBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Book extends BaseBook<Book> {
	public static final Book dao = new Book().dao();
}
