package com.model;

import com.model.pojo.BaseItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Item extends BaseItem<Item> {
	public static final Item dao = new Item().dao();
}
