package com.model;

import com.model.pojo.BaseUpload;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Upload extends BaseUpload<Upload> {
	public static final Upload dao = new Upload().dao();
}
