package com.model;

import com.model.pojo.BaseUserTokens;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTokens extends BaseUserTokens<UserTokens> {
	public static final UserTokens dao = new UserTokens().dao();
}
