package com.model;

import com.model.pojo.BaseUser;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();

	public List<Upload> getUpload(){
		return Upload.dao.find("select * from upload where id=?",
				get("id"));
	}
}
