package com.common.model;

import com.common.model.base.BaseRegister;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Register extends BaseRegister<Register> {
	public static final Register dao = new Register().dao();
}
